# Generated by Django 4.2.21 on 2025-08-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('duration_years', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('CLINICAL', 'Clinical')], max_length=16)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['term__syllabus__program__short_name', 'term__syllabus__name', 'term__term_number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='resources.program')),
            ],
            options={
                'ordering': ['program__short_name', 'name'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term_number', models.PositiveSmallIntegerField(help_text='1 for first term, 2 for second, etc.')),
                ('term_type', models.CharField(choices=[('SEMESTER', 'Semester'), ('YEAR', 'Year')], max_length=16)),
                ('name', models.CharField(blank=True, help_text='Optional display name', max_length=100)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='resources.syllabus')),
            ],
            options={
                'ordering': ['syllabus__program__short_name', 'syllabus__name', 'term_number'],
                'unique_together': {('syllabus', 'term_number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Direct URL to the study material')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='resources.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='resources.term'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('term', 'code')},
        ),
    ]
