# Generated by Django 4.2.21 on 2025-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
