# Generated by Django 4.2.21 on 2025-08-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_populate_subject_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or identifier', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Color theme for UI', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subjectmaterial',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='month',
            field=models.CharField(blank=True, help_text="Month for PYQs (e.g., 'July', 'December')", max_length=20),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year for PYQs and time-sensitive materials', null=True),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='resources.materialtype'),
        ),
    ]
