# Generated by Django 4.2.21 on 2025-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_materialtype_alter_subjectmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmaterial',
            name='month',
            field=models.CharField(blank=True, help_text="Month for PYQs (e.g., 'July', 'December')", max_length=20, null=True),
        ),
    ]
