# Generated by Django 4.2.23 on 2025-09-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_subjectmaterial_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaterial',
            options={},
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='month',
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='url',
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='year',
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='file',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='file_size',
            field=models.FloatField(blank=True, help_text='Size in KB', null=True),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.subject'),
        ),
    ]
