# Generated by Django 4.2.21 on 2025-09-01 19:53

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_subjectmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmaterial',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='cloudinary_url',
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='subjectmaterial',
            name='file_type',
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='resources.materialtype'),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='month',
            field=models.CharField(blank=True, help_text="Month for PYQs (e.g., 'July', 'December')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='url',
            field=models.URLField(blank=True, help_text='Auto-filled Cloudinary URL'),
        ),
        migrations.AddField(
            model_name='subjectmaterial',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year for PYQs and time-sensitive materials', null=True),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjectmaterial',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='resources.subject'),
        ),
    ]
